### ISSUE TITLE
Error: [Ruvyrias Error] No Session ID found.

### ISSUE THREAD

**Issue by deadshotofficial** [DarkslayerHaos/ruvyrias#2]
While Testing a Bot made in Ruvyrias, I found this error:
Ruvyrias Version: 1.3.7 
Lavalink Version: 4
![image](https://github.com/DarkslayerHaos/ruvyrias/assets/63696670/51de123e-5966-4ff2-b546-29d8319ddfc4)

**Comment by DarkslayerHaos** [comment]
> While Testing a Bot made in Ruvyrias, I found this error: Ruvyrias Version: 1.3.7 Lavalink Version: 4 ![image](https://private-user-images.githubusercontent.com/63696670/327145616-51de123e-5966-4ff2-b546-29d8319ddfc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1NzUyNzMsIm5iZiI6MTcxNDU3NDk3MywicGF0aCI6Ii82MzY5NjY3MC8zMjcxNDU2MTYtNTFkZTEyM2UtNTk2Ni00ZmYyLWI1NDYtMjlkODMxOWRkZmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDE0NDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NGQ2NGE0ZDhiNzA4NDhkYTgzYWRkYWQyNDhhNTQyMzE4NTlhODIyZDZmN2JlYTQzZTBkYTk2ZjE5MGM0ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.26rmXLp7UbCi1wx5QPA4NMuIiYciih9a_fuaGjnGe94)

Isn't an issue, it's just warning you that the voice channel the bot are trying to connect isn't available anymore or something like that.
After all, how will the Ruvyrias send data package to a voice channel that doesn't exists?

But if you have an step-by-step to reproduce would be good, just to guarantee the integrity of methods and execution.

**Comment by deadshotofficial** [comment]
> But if you have an step-by-step to reproduce would be good, just to guarantee the integrity of methods and execution.
I tried to reproduce it but couldn't .. maybe i messed up somewhere while testing ..
